#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Dec  1 13:39:49 2008

import wx
import wx.grid
import os 
import os.path

# begin wxGlade: extracode
# end wxGlade

class MyMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyMenuBar.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        self.no1 = wx.Menu()
        self.Append(self.no1, "Edition")
	self.no1.Append(-1, "Delete")
	self.no1.Append(-1, "Addition")
	self.no1.AppendSeparator()
	self.no1.Append(-1, "")
        self.no2 = wx.Menu()
        self.Append(self.no2, "Classifation")
	self.no2.Append(-1, "By BookName")
	self.no2.Append(-1, "By AuthorName")
	self.no2.Append(-1, "By Publication")
	self.no2.AppendSeparator()
	self.no2.Append(-1, "")
        self.wxglade_tmp_menu = wx.Menu()
        self.Append(self.wxglade_tmp_menu, "Help")
	self.wxglade_tmp_menu.Append(-1, "About")
	self.wxglade_tmp_menu.AppendSeparator()
        self.wxglade_tmp_menu.Append(-1,"")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyMenuBar.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyMenuBar.__do_layout
        pass
        # end wxGlade

# end of class MyMenuBar


class MyPems(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyPems.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
	
	#self.scroll = wx.ScrolledWindow(self, -1,(600,400))
	#self.scroll.SetScrollbars(1, 1, 600, 400)
	self.label1 = wx.StaticText(self, -1, "Input key words:")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "",size=(50,-1))
        self.button_1 = wx.Button(self, -1, "Search")
        self.list_box_1 = wx.ListBox(self, -1, choices=[])
        self.grid_1 = wx.grid.Grid(self, -1, size=(1, 1))
        self.static_line_1 = wx.StaticLine(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyPems.__set_properties
        self.SetTitle("PEMS")
        self.SetSize((800, 602))
        self.grid_1.CreateGrid(10, 3)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyPems.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.label1, 4, wx.ALL, 0)
        sizer_4.Add(self.text_ctrl_1, 10, 0, 0)
        sizer_4.Add(self.button_1, 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add(self.list_box_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.grid_1, 3, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 18, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_1, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.SetSize((800, 602))
        # end wxGlade

	MyMenu = MyMenuBar()
	self.SetMenuBar(MyMenu)
# end of class MyPems





class MyToolBar(wx.ToolBar):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyToolBar


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyPems(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
